stream_urls = [
     "https://twitch.tv/gogcom",
     "https://twitch.tv/l34um1",
     "https://twitch.tv/markiplier",
     "https://twitch.tv/wanderbot",
     "https://twitch.tv/memoriesin8bit",
     "https://twitch.tv/aavak",
     "https://twitch.tv/venomvelind",
]
