# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

#=== CUSTOM VARS ===#

# Editor
export EDITOR="vim"
export VISUAL=$EDITOR

# Go
export PATH=$PATH:$HOME/go/bin

# GPG
export GPG_TTY=$(tty)

# Java
export JAVA_HOME=/usr/lib/jvm/openjdk
export PATH=$PATH:/usr/lib/jvm/java-8-openjdk/bin

# Ledger
export LEDGER_FILE=$HOME/nextcloud/accounting/personal.ledger

# Nix
. ~/.nix-profile/etc/profile.d/nix.sh

# Node
export PATH=$PATH:/home/brightone/.yarn/bin

# Path
export PATH="$PATH:/bin:/usr/bin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/lib/jvm/default/bin:$HOME/.local/bin"

# Rust
export PATH=$PATH:$HOME/.cargo/bin
export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"
