#!/bin/bash

### Helpers

c() {
    C=${1}
}

n() {
    echo -e "==> ${C}: ${1}..."
}

clone() {
    # Check if $2 exists. If not, clone $1 to $2.
    [[ -a "$2" ]] && echo "$2 already exists, skipping..." >&2 || git clone "$1" "$2"
}

### End helpers

c "yadm"

n "installing envtpl through pip"
pip3 install --user envtpl

c "emacs"

n "cloning doom-emacs"
clone git@gitlab.com:BrightOne/doom-emacs.git ~/.emacs.d.doom

n "cloning spacemacs"
clone https://github.com/syl20bnr/spacemacs ~/.emacs.d.spacemacs

c "passwords"

n "cloning passwords"
clone git@gitlab.com:BrightOne/passwords.git ~/.password-store

c "zplugin"

n "installing zplugin via curl"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh)"

n "removing errorful prompts"
rm -rf $HOME/.zplugin/snippets/https--github.com--sorin-ionescu--prezto--trunk--modules/prompt/functions/prompt_{agnoster,powerlevel9,powerline,pure}_setup
